"""create department_position table

Revision ID: 2b6b97cde912
Revises: 5b409de2aa29
Create Date: 2024-11-07 16:14:35.609820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b6b97cde912"
down_revision: Union[str, None] = "5b409de2aa29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departament_position",
        sa.Column("departament_id", sa.Integer(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["departament_id"],
            ["departments.id"],
            name=op.f("fk_departament_position_departament_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_departament_position_position_id_positions"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("departament_position")
    # ### end Alembic commands ###
